-- setlocal textwidth=79
-- if executable('flake8')
--   setlocal makeprg=flake8\ %:S
--   setlocal errorformat=%f:%l:%c:\ %t%n\ %m
-- endif
-- if executable('black')
--   setlocal formatprg=black\ -q\ -
-- elseif executable('autopep8') |
--   setlocal formatprg=autopep8\ -
-- endif
vim.opt_local.textwidth = 79
