# Disable the blank line at the start of the prompt
add_newline = false

# Make the prompt a single line.
[line_break]
disabled = true

[git_status]
ahead = "⇡"
behind = "⇣"

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[rust]
symbol = " "

[lua]
symbol = " "

[julia]
symbol = " "

[perl]
symbol = " "

[ruby]
symbol = " "

[package]
disabled = true
